### ISSUE TITLE
Add event error 403

### ISSUE THREAD

**Issue by ibasaw** [Djamy/GoogleCalendarBundle#6]
What is the attendee email to pass to the method addEvent ?

When i try to add an event, got this error:

```
  [Google_Service_Exception]
  Error calling POST https://www.googleapis.com/calendar/v3/calendars/xxx/events: (403) Forbidden
```

**Comment by Djamy** [comment]
Hi,

Like described [here](https://github.com/Djamy/GoogleCalendarBundle/blob/master/Service/GoogleCalendarService.php#L81): you should add the calendar owner to the attendees list.

That said, `$eventAttendee` should be an array with your attendees' emails inside.
I'll try to do the fix this weekend but feel free to make a PR if you wish.

**Comment by ibasaw** [comment]
i tried with an array, but always got this error

**Comment by ibasaw** [comment]
in fact you must share the calendar with the email google cloud api, if not you'll got this error
